### ISSUE TITLE
TRIED target comes up when target wrong, but route not done

### ISSUE THREAD

**Issue by coleshaw** [wombats-writing-code/fbw-student#1]

**Comment by coleshaw** [comment]
screenshot attached

![captura de pantalla 2016-12-13 a las 3 31 02 pm](https://cloud.githubusercontent.com/assets/4930129/21159415/26c546fc-c14f-11e6-828a-89b484361009.png)

**Comment by luwen-huang** [comment]
actually, this isn't a bug, but a reflection of the data. This happens whenever the selected choice for the given Target question has no tagged learning outcomes ==> no next question. 

I've replicated the bug using this question. See screenshots. That's why when you go back to it later, e.g. click on Subjects then Missions, the Target sign changes to Red, because submit 

 I've fixed the check for `hasNavigated` so that it checks dynamically, so we don't have to worry about updates. This means changes to `updateAssessmentSectionsWithRespons` and the selectors in fbw-platform-common.
