### ISSUE TITLE
can't get mission sections on iOS

### ISSUE THREAD

**Issue by luwen-huang** [wombats-writing-code/fbw-student#44]
Fire up the iOS version, login using d2l, select the subject, click on the 1st mission, it tries to load the mission questions but then gets this error:

<img width="617" alt="screen shot 2017-01-25 at 12 49 54 pm" src="https://cloud.githubusercontent.com/assets/2822290/22278279/10b9fc66-e2fd-11e6-9ee5-c5b32a269894.png">

It's probably something stupid, like not passing in the proper bank id when you select a mission...tests pass on middleman and the web version works fine. But it's pretty much the same -- look at the ios `Missions.js` view upon `_onSelectMission`

**Comment by coleshaw** [comment]
You get further than I do....I can't even get to the list of missions. This is the error I get after clicking on the `subject`.

![captura de pantalla 2017-01-25 a las 9 24 24 am](https://cloud.githubusercontent.com/assets/4930129/22294140/242add82-e2e0-11e6-98e8-d3bfb0055e59.png)

**Comment by coleshaw** [comment]
After `npm install`, I get this `babelHelpers.typeof` error. I think this is because of the babel presets in fbw-platform-common.

http://stackoverflow.com/questions/35563025/new-react-native-app-has-typeerror-babelhelpers-typeof-is-not-a-function-ios

Will try to update RN, etc.

![captura de pantalla 2017-01-25 a las 1 59 36 pm](https://cloud.githubusercontent.com/assets/4930129/22304718/97d5da2c-e306-11e6-9f49-feaa9bb34534.png)

**Comment by luwen-huang** [comment]
confirmed that the original bug was the Flutter Nutter #46 problem. will get iOS up to speed and then if @cjshawMIT still has trouble getting RN started, let's open up another issue.
